💨 Support plain object as key for caching
unitoio/cachette pull request #56
Opened 2021-07-19 15:21 UTC by jehan-rubin

When we have a plain object as an argument in a function call that is cached, we are not able to create different keys as cacheKey even if the object is not the same in 2 different calls. This behavior results in fetching the wrong result for a call that has been cached before. 

This PR introduces the support of plain object in `buildCacheKey` function.

We basically get all the values of the plain object and join them with `-` char. In the case of: 

```
getFoo(
	arg1 = 'coucou',
	arg2 = { nestedProp = 'nestedValue', nestedProp2 = 'nestedValue2' },
)
```
Will lead to this cacheKey: `getFoo-coucou-nestedValue-nestedValue2`.

2021-07-19 15:49 UTC, gregsavoie approved these changes
![](https://media0.giphy.com/media/4TgADFrAKzq2wKyomS/giphy-downsized-medium.gif)

2021-07-19 17:16 UTC, louib commented on src/lib/CacheClient.ts
> +          return Object.values(x).join('-');
@jehan-rubin should we not also include the keys of the object in the generated cache key. Also, what about nested objects?

2021-07-19 19:36 UTC, jehan-rubin commented on src/lib/CacheClient.ts
> +          return Object.values(x).join('-');
We could, just to be sure it will be always unique. You are right we should support nested objects as well, I will take a look.

2021-07-20 15:37 UTC, ronjouch commented on src/lib/CacheClient.ts
> +          return Object.values(x).join('-');
@jehan-rubin one more thing: you need to sort the object by key. Else caching of `{a: 1, b: 2}` will be missed when calling `{b: 2, a: 1}`

2021-07-20 15:38 UTC, jehan-rubin commented on src/lib/CacheClient.ts
> +          return Object.values(x).join('-');
Oh nice, make sense!  🙏

2021-07-20 15:38 UTC, ronjouch requested changes

2021-07-20 15:38 UTC, ronjouch commented on test/CacheClient_test.ts
> +    it('will convert plain object values', async () => {
Once you have added sorting, pls also add a test that `{a: 1, b: 2}` and `{b: 2, a: 1}` resolve to the same cache key

2021-07-20 15:43 UTC, ronjouch commented
@jehan-rubin hmmmmmmmmm also: how will this behave with a key:value where value is array, and maybe a huge one? Do we want to accept arrays (stringify them), or only beyond a certain legth, or not at all and throw?

2021-07-20 15:51 UTC, jehan-rubin commented
> @jehan-rubin hmmmmmmmmm also: how will this behave with a key:value where value is an array, and maybe a huge one? Do we want to accept arrays (stringify them), or only beyond a certain legth, or not at all and throw?

@ronjouch Mmmh, we could do a `join('-')` on the arrays. But not sure what could be the limit tho? we could really finish with a really big key, but we could have the same result with a big object. Do you think it could be a problem?

2021-07-20 15:57 UTC, ronjouch commented on test/CacheClient_test.ts
> +    })
Separate tests, por favor.

2021-07-20 15:59 UTC, ronjouch commented
> Mmmh, we could do a `join('-')` on the arrays. But not sure what could be the limit tho? we could really finish with a really big key, but we could have the same result with a big object. Do you think it could be a problem?

@jehan-rubin we use this to cache function calls. A function taking one (or a few) object param will typically have a few keys (say a dozen max, which are okay stringified for a key).

However, we do have calls that take array params that can be huge (say, a list of hundreds of tasks). In this case, yeah supporting arrays indiscriminately will lead into trouble (I don't know when exactly, as I don't know the limits of Redis keys). I'm not too sure what to do here; we don't have a logger to warn, and throwing beyond a certain limit will certainly lead to prod surprise trouble.

@erykwarren @louib any thoughts about this?

2021-07-20 17:39 UTC, erykwarren reviewed
As for the huge keys, I would just throw if the key is longer than some max length (cc @ronjouch)

2021-07-20 17:39 UTC, erykwarren commented on src/lib/CacheClient.ts
> +      .filter(x =>
How about handling `undefined` and `null` too? In those cases, you can do `new String(x).valueOf()`

Otherwise, there is a potential collision between `('a', undefined, 1)` and `('a', 1, undefined)`

2021-07-20 17:39 UTC, erykwarren commented on src/lib/CacheClient.ts
> +      .filter(x =>
Also, I am not sure that the filter does anything now...

2021-07-20 18:51 UTC, jehan-rubin commented on src/lib/CacheClient.ts
> +      .filter(x =>
Mmmh, it would make sense to support undefined and null. Also, the filter still filters out the non-plain objects. But I can definitely simplify this tho.

2021-07-23 13:40 UTC, Urik approved these changes

2021-07-23 13:40 UTC, Urik commented on src/lib/CacheClient.ts
> +          }).join('-');
This should work, but is there a reason for not doing `JSON.stringify`? Performance?

2021-07-23 13:46 UTC, Urik commented on src/lib/CacheClient.ts
> +          }).join('-');
@jehan-rubin one potential edge case we should be weary of is, objects with circular references will turn this into an infinite loop, at least until the stack fills up and we crash

2021-07-23 13:53 UTC, jehan-rubin commented on src/lib/CacheClient.ts
> +          }).join('-');
> This should work, but is there a reason for not doing `JSON.stringify`? Performance?

@Urik The main reason is I wanted to keep the same structure as before, and we can sort the key of the object to be sure that two equal objects but with different keys order will not be considered as two different objects!

About the circucal references, I'm not sure what are the chance that something like that happen 🤔 I'm applying the caching only on plain object so not sure it could happen

2021-07-23 14:42 UTC, jehan-rubin commented on src/lib/CacheClient.ts
> +    }
@erykwarren  @ronjouch I tried to find some best practices about key length for Redis, didn't find anything. I may have missed something tho. I just found this benchmark based on the length of the keys: https://adamnengland.wordpress.com/2012/11/15/redis-performance-does-key-length-matter/

I picked 1000 based on this benchmark. It seems to be the less impactful value for write/read. But I'm not sure that we can really rely on these results (and it's a bit old). What do you think?

Also, it will probably throw a lot if we start to cache function with an array of objects.

2021-07-23 14:52 UTC, Urik commented on src/lib/CacheClient.ts
> +    }
I'm not sure about this. 1000 seems pretty short to me and write times are barely impacted. If throwing here causes us not to cache the call, then the reads will be longer than if we cached anyway.

Something interesting from the Redis documentation: https://redis.io/topics/data-types-intro
> Very long keys are not a good idea. For instance a key of 1024 bytes is a bad idea not only memory-wise, but also because the lookup of the key in the dataset may require several costly key-comparisons. Even when the task at hand is to match the existence of a large value, hashing it (for example with SHA1) is a better idea, especially from the perspective of memory and bandwidth.

We could say "if the key length is longer than 500, let's hash it, otherwise let's just use the normal key".

2021-07-23 14:58 UTC, ronjouch commented on src/lib/CacheClient.ts
> +          }).join('-');
I'm not too freaked out about circular references. Remind the use case is function calls. Although we do have circular references here and there (e.g. in SBIG), when do you write _function arguments_ that are objects with circular references? Never, I think.

But still, yeah it could happen and bork things up.

→ @jehan-rubin @Urik  what about detecting circular references, and throw if there is one? (With a new test for it). I think the best way to do this is simply to attempt to `JSON.stringify` and see if you get a `TypeError: cyclic object value`; https://stackoverflow.com/questions/14962018/detecting-and-fixing-circular-references-in-javascript/59833943#59833943 .

2021-07-23 15:01 UTC, jehan-rubin commented on src/lib/CacheClient.ts
> +    }
That's a good idea, will do instead of throwing!

2021-07-23 15:15 UTC, Urik commented on src/lib/CacheClient.ts
> +          }).join('-');
@ronjouch @jehan-rubin 
I've just played a bit with V8's `serialize` method and it could be cool, check this out:  

```
> let a = require('v8')
undefined
> a.serialize({a: 1, b: 2})
<Buffer ff 0d 6f 22 01 61 49 02 22 01 62 49 04 7b 02>
> a.serialize({b:2, a: 1})
<Buffer ff 0d 6f 22 01 62 49 04 22 01 61 49 02 7b 02> // v8.serialize returns the same result regardless of keys order
> let b = {a: 1}
undefined
> a.serialize(b)
<Buffer ff 0d 6f 22 01 61 49 02 7b 01>
> a.deserialize(a.serialize(b))
{ a: 1 }
> b.b = b
<ref *1> { a: 1, b: [Circular *1] }
> b
<ref *1> { a: 1, b: [Circular *1] }
> a.serialize(b)
<Buffer ff 0d 6f 22 01 61 49 02 22 01 62 5e 00 7b 02> // v8.serialize can serialize circular structures
> a.deserialize(a.serialize(b))
<ref *1> { a: 1, b: [Circular *1] } // v8.serialized stuff can reconstructed to its real values
> a.serialize(b).toString('base64')
'/w1vIgFhSQIiAWJeAHsC' // v8.serialized stuff can be transformed into a unique string
> a.deserialize(Buffer.from('/w1vIgFhSQIiAWJeAHsC', 'base64'))
<ref *1> { a: 1, b: [Circular *1] }
```
If the objective is transforming an object into a unique string, then `v8.serialize(theObject).toString('base64')` could work nicely.

2021-07-23 15:17 UTC, ronjouch commented on src/lib/CacheClient.ts
> +          }).join('-');
> If the objective is transforming an object into a unique string, then `v8.serialize(theObject).toString('base64')` could work nicely.

@Urik I like it in theory, but to my eyes, developer friendliness/debuggability goes to the bin too much for a solution like this to be likeable.

2021-07-23 15:19 UTC, Urik commented on src/lib/CacheClient.ts
> +          }).join('-');
Mmmkay, if having a readable key is important though, please check this because it'll make non readable keys:
https://github.com/unitoio/cachette/pull/56#discussion_r675626150

2021-07-23 15:21 UTC, ronjouch commented on src/lib/CacheClient.ts
> +          }).join('-');
> Mmmkay, if having a readable key is important though, please check this because it'll make non readable keys: [#56 (comment)](https://github.com/unitoio/cachette/pull/56#discussion_r675626150)

@Urik @jehan-rubin yeah, not a fan of the hashing, and having two wildly different kinds of keys in Redis. I'd rather throw and reevaluate why we're in this situation.

Also, SHA1 collisions happened.

2021-07-23 15:23 UTC, ronjouch commented on src/lib/CacheClient.ts
> +    }
@Urik @jehan-rubin I'm not a fan of the hashing, and having two wildly different kinds of keys in Redis, including an inscrutable one. I'd rather throw and reevaluate why we're in this situation.

2021-07-23 15:27 UTC, jehan-rubin commented on src/lib/CacheClient.ts
> +    }
@ronjouch Make sense, and for debugging purposes losing the readability of the key is not the best. Anyway, I think you are right, if we are in the situation where we cache a call with a really big key, that must be something to improve in the function implementation rather than increasing allowed key length in cachette 🤔

2021-07-23 15:32 UTC, jehan-rubin commented on src/lib/CacheClient.ts
> +    }
@ronjouch @Urik I will let 1000 chars max for now, monitor the changes, and reevaluate the value if need be.

I pushed the check for circular references 🙏

2021-07-23 15:33 UTC, Urik commented on src/lib/CacheClient.ts
> +    }
Then I'd entirely disable caching objects, and manually cache in our projects using `cacheInstance.getOrFetchValue`?
Having a situation where we may or may not cache a function depending on the size of an object we sent to it feels kinda janky to me.

Again, why throw? Redis *can* handle key sizes of up to 512 MB and it's mostly read speeds that are impacted. The chance of us doing many costly reads against these keys are pretty short as well, aren't they?

2021-07-23 15:45 UTC, Urik commented on src/lib/CacheClient.ts
> +    }
Nevermind, we only use `.cached` in connectors, so I think this will be ok

2021-07-23 18:01 UTC, Urik approved these changes

2021-07-26 17:41 UTC, merged

2021-07-27 00:20 UTC, erykwarren commented on src/lib/CacheClient.ts
> +        return new String(x).valueOf();
@jehan-rubin The filtering followed by a map-if feels weird. Seems like the condition logic is spread in two places. How about doing the map part only?

2021-07-27 00:45 UTC, jehan-rubin commented on src/lib/CacheClient.ts
> +        return new String(x).valueOf();
Mmmh, you are right I could probably re-work this part 🤔